# global handlers
handlers=java.util.logging.ConsoleHandler, java.util.logging.FileHandler

# global log level
.level=INFO

# FileHandler Configuration
java.util.logging.FileHandler.pattern=logs/app-%g.log
java.util.logging.FileHandler.level=INFO
java.util.logging.FileHandler.limit=5242880
java.util.logging.FileHandler.count=5
java.util.logging.FileHandler.append=true
java.util.logging.FileHandler.formatter=java.util.logging.SimpleFormatter

# --- ConsoleHandler Configuration ---
java.util.logging.ConsoleHandler.level=INFO
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
