package dev.luhwani.output;

import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;

import com.fasterxml.jackson.databind.ObjectMapper;

import dev.luhwani.model.AnalysisResult;
import dev.luhwani.model.Checkpoint;
import dev.luhwani.model.QueueEvent;
import dev.luhwani.model.QueueEvent.Item;
import dev.luhwani.model.TweetDecision;
import dev.luhwani.tweetEvaluation.BatchFailureHandler;
import dev.luhwani.tweetEvaluation.RequestExecutor;

/**
 * Writes {@code output.csv} and {@code checkpoint.json}. It consumes
 * the
 * {@link AnalysisResult} s generated by the {@link RequestExecutor}.
 * The results are stored in a {@code resultQueue}, and the class that
 * initializes the outputWriter and the RequestExecutor should use the same
 * instance of a {@code BlockingQueue<QueueEvent<AnalysisResult>>}
 * inside the constructor of both classes.
 * <p>
 * The second shared attribute is named {@code failedBatchToLastTweetMap}.
 * It is also shared between this class and the RequestExecutor, and
 * is only functional when we are not retrying failed batches. The
 * class initializing the OutputWriter and the RequestExecutor should
 * use a thread safe map, as multiple threads will produce into the queue
 * <p>
 * The last shared attribute is the
 * {@code BlockingQueue<QueueEvent<Integer>> successfulRetriedBatches},
 * and it is shared between this class and the {@link BatchFailureHandler}.
 * It's function is to mark failed batches that have been successfully retried
 * and can be removed from {@code failedbatches.jsonl}
 * by the BatchFailureHandler. Although, this attribute is only functional
 * if we are retrying. On normal runs, it is not used in the audit process.
 *
 */
public final class OutputWriter implements AutoCloseable {

    private final ExecutorService executor;
    private final BufferedWriter writer;
    private final ObjectMapper objectMapper;
    private final Path checkpointPath;
    private final TreeMap<Integer, AnalysisResult> pending;

    private final BlockingQueue<QueueEvent<AnalysisResult>> resultQueue;
    private final Map<Integer, String> failedBatchToLastTweetMap;
    private final BlockingQueue<QueueEvent<Integer>> successfulRetriedBatches;

    private Future<?> task;
    private Integer nextExpectedBatchNumber;
    private Checkpoint checkpoint;

    public OutputWriter(BlockingQueue<QueueEvent<AnalysisResult>> resultQueue,
            Map<Integer, String> failedBatchToLastTweetMap,
            Path checkpointPath, ObjectMapper objectMapper, Path outputPath, Path failurePath,
            int nextExpectedBatchNumber,
            BlockingQueue<QueueEvent<Integer>> successfulRetriedBatches)
            throws IOException {
        this.executor = Executors.newSingleThreadExecutor();
        this.objectMapper = objectMapper;
        this.checkpointPath = checkpointPath;
        this.resultQueue = resultQueue;
        this.failedBatchToLastTweetMap = failedBatchToLastTweetMap;
        this.writer = Files.newBufferedWriter(outputPath, StandardCharsets.UTF_8,
                StandardOpenOption.CREATE,
                StandardOpenOption.APPEND);
        this.nextExpectedBatchNumber = nextExpectedBatchNumber;
        pending = new TreeMap<>();
        this.successfulRetriedBatches = successfulRetriedBatches;
        checkpoint = new dev.luhwani.tweetProcessing.CheckpointResolver(checkpointPath, outputPath, failurePath,
                objectMapper).load();
    }

    /**
     * Starts the background consumer that writes results and checkpoints.
     * 
     * @param isRetrying whether the results are retries of failed batches
     */
    public void start(boolean isRetrying) {
        task = executor.submit(() -> {
            try {
                handleResult(isRetrying);
            } catch (InterruptedException | IOException e) {
                Thread.currentThread().interrupt();
                throw new RuntimeException(e);
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        });
    }

    /**
     * Waits for the writer task and propagates failures from it.
     * 
     * @throws ExecutionException if the writer task fails
     */
    public void awaitCompletion() throws ExecutionException {
        try {
            task.get();
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new RuntimeException(e);
        }
    }

    /**
     * Consumes result events, writes CSV rows, and updates the checkpoint.
     * Normal processing waits for the next expected batch; retry processing
     * appends successful retries as they arrive.
     * 
     * @param isRetrying , to specify if we're retrying failed
     *                   batches or not.
     * @throws IOException
     * @throws InterruptedException
     */
    private void handleResult(boolean isRetrying) throws IOException, InterruptedException {
        while (true) {
            while (failedBatchToLastTweetMap.containsKey(nextExpectedBatchNumber)) {
                Set<Integer> failures = checkpoint.getFailedBatches();
                failures.add(nextExpectedBatchNumber);
                int lastProcessedBatch = nextExpectedBatchNumber;
                String lastTweet = failedBatchToLastTweetMap.get(nextExpectedBatchNumber);
                checkpoint = new Checkpoint(checkpoint.getSuccessfulBatches(), failures, lastProcessedBatch, lastTweet);
                updateCheckpoint(checkpoint);
                nextExpectedBatchNumber++;
            }
            QueueEvent<AnalysisResult> event = resultQueue.poll(500, TimeUnit.MILLISECONDS);
            if (event == null) {
                continue;
            }
            if (event instanceof QueueEvent.End) {
                if (isRetrying) {
                    successfulRetriedBatches.add(QueueEvent.End.instance());
                }
                break;
            }
            QueueEvent.Item<AnalysisResult> item = (Item<AnalysisResult>) event;
            AnalysisResult result = item.value();
            if (isRetrying) {
                Integer batchNumber = result.batchNumber();
                Set<Integer> successes = checkpoint.getSuccessfulBatches();
                Set<Integer> failures = checkpoint.getFailedBatches();
                successes.add(batchNumber);
                failures.remove(batchNumber);
                checkpoint = new Checkpoint(successes, failures, checkpoint.getLastProcessedBatch(),
                        checkpoint.getLastProcessedTweet());
                write(result);
                updateCheckpoint(checkpoint);
                successfulRetriedBatches.add(new QueueEvent.Item<Integer>(batchNumber));
                continue;
            }
            pending.put(result.batchNumber(), result);
            while (pending.containsKey(nextExpectedBatchNumber)) {
                AnalysisResult ready = pending.remove(nextExpectedBatchNumber);
                Set<Integer> successes = checkpoint.getSuccessfulBatches();
                successes.add(nextExpectedBatchNumber);
                int lastProcessedBatch = ready.batchNumber();
                String lastTweet = ready.results().getLast().tweetId();
                checkpoint = new Checkpoint(successes, checkpoint.getFailedBatches(), lastProcessedBatch, lastTweet);
                write(ready);
                updateCheckpoint(checkpoint);
                nextExpectedBatchNumber++;
            }
        }
    }

    // TODO: how do we make these two methods below atomic?
    private void write(AnalysisResult result) throws IOException {
        for (TweetDecision decision : result.results()) {
            writer.write(result.batchNumber().toString());
            writer.write(",");
            writer.write("https://x.com/i/status/" + decision.tweetId());
            writer.write(",");
            writer.write(decision.decision().name());
            writer.write(",");
            writer.write(cleanForCsv(decision.reason()));
            writer.newLine();
        }
        writer.flush();
    }

    private void updateCheckpoint(Checkpoint checkpoint) throws IOException {
        objectMapper.writeValue(checkpointPath.toFile(), checkpoint);
    }

    private String cleanForCsv(String input) {

        if (input == null) {
            return "";
        }

        String cleaned = input.trim();

        cleaned = removeControlCharacters(cleaned);

        cleaned = cleaned.replace("\"", "\"\"");

        if (needsQuoting(cleaned)) {
            cleaned = "\"" + cleaned + "\"";
        }
        return cleaned;
    }

    private String removeControlCharacters(String value) {
        return value
                .replace("\r\n", " ") // Windows line ending
                .replace("\n", " ") // Unix line ending
                .replace("\r", " "); // Old Mac line ending
    }

    private boolean needsQuoting(String value) {
        return value.contains(",") || value.contains("\"") || value.contains("\n") || value.contains("\r");
    }

    @Override
    public void close() throws Exception {
        executor.shutdown();
        executor.awaitTermination(3000, TimeUnit.MILLISECONDS);
    }

}
